### ISSUE TITLE
Purge user event not work

### ISSUE THREAD

**Issue by nlgtuankiet** [googleapis/java-recommendations-ai#155]
I'm facing this issue using both REST API and the client library. The response looking something like
```
curl -X POST -H "Authorization: Bearer "$(gcloud auth print-access-token blabla)"" \
      -H "Content-Type: application/json; charset=utf-8" \
     --data '{
              "filter":"eventTime<\"2020-09-17T18:25:43.511Z\"",
              "force":"false" 
    }' \
    "https://recommendationengine.googleapis.com/v1beta1/projects/blabla/locations/global/catalogs/default_catalog/eventStores/default_event_store/userEvents:purge"
```
```
{
  "name": "purge-userevents-default_catalog-default_event_store-11256037574273429083"
}
```
I think this suppose to list the event that about to be deleted, setting force to true/false or any filter return the same result.

**Comment by chingor13** [comment]
It looks like [this RPC](https://cloud.google.com/recommendations-ai/docs/reference/rest/v1beta1/projects.locations.catalogs.eventStores.userEvents/purge) returns an Operation (long running process) and does not complete immediately. For operations like these, you'll want to poll the operation until it succeeds.

If you are using google-cloud-recommendations-ai client library, [`purgeUserEventsAsync`](https://googleapis.dev/java/google-cloud-recommendations-ai/latest/com/google/cloud/recommendationengine/v1beta1/UserEventServiceClient.html#purgeUserEventsAsync-java.lang.String-java.lang.String-boolean-) should be handling the polling of the long running operation for you.

**Comment by nlgtuankiet** [comment]
It has been 3 months since I trigger the purge request, nothing happened since then unfortunately

**Comment by dirkbosman** [comment]
Still having this same problem.... 

Triggering the following request with `"force":"true"`
`https://recommendationengine.googleapis.com/v1beta1/projects/<project-id>/locations/global/catalogs/default_catalog/eventStores/default_event_store/userEvents:purge`

gives me the operation-id, but once I trigger the curl request against the following operation: 
`https://recommendationengine.googleapis.com/v1beta1/projects/<project-id>/locations/global/catalogs/default_catalog/operations/purge-userevents-default_catalog-default_event_store-<operation>`

It does nothing....

Any updates on this?
