### ISSUE TITLE
google-cloud-recommendations-ai vs google-cloud-retail

### ISSUE THREAD

**Issue by rotilho** [googleapis/java-recommendations-ai#290]
Docs says that we should use retail api however it seems recommendations java api still actively developed. Which one should be used?

Besides, we need better docs and error messages. Use google-cloud-retail and google-cloud-recommendations-ai have been a constant trial and error and often I need to guess what the problem is.

**Comment by Neenu1995** [comment]
Hi @rotilho 

Thank you for reaching out. 
`google-cloud-recommendations-ai` is a beta library. This makes it a work-in-progress, and may occasionally make backwards-incompatible changes.`google-cloud-retail` is the GA version and hence stable.

We are always working on our libraries and documentation. Thank you for your feedback.
