### ISSUE TITLE
java-recommendations-ai: When write/import UserEvent (purchase-complete) transaction.revenue field is missing and service throws an exception

### ISSUE THREAD

**Issue by nielran** [googleapis/java-recommendations-ai#343]
I am trying to import purchase-complete UserEvent with a Spring Batch application, using google-cloud-recommendations-ai java api, version 0.6.0. And I'm always getting error   transaction.revenue field is missing even though this filed is set.

Current environment is:
- Windows 10 Pro (local environment)
- Java 8 and 11

This is how I build UserEvent
```java
ProductEventDetail.Builder productEventDetailBuilder = ProductEventDetail.newBuilder().setPurchaseTransaction(
              PurchaseTransaction.newBuilder().setId("223").setCurrencyCode("EUR").setRevenue(12.3f).build()
      ).addProductDetails(ProductDetail.newBuilder().setQuantity(2).setId("0034612").setCurrencyCode("EUR").build());
UserEvent userEvent = UserEvent.newBuilder().setUserInfo(UserInfo.newBuilder().setVisitorId("032134").build())
        .setEventTime(Timestamp.newBuilder().setSeconds(1592833306).build())
        .setProductEventDetail(productEventDetailBuilder.build())
        .setEventSource(UserEvent.EventSource.BATCH_UPLOAD)
        .setEventType("purchase-complete").build();
```
And this is how I call Recommendations api: 

```java
String parent = EventStoreName.of("[PROJECTID]", "global", "default_catalog", "default_event_store").toString();
ImportUserEventsRequest importUserEventRequest = ImportUserEventsRequest.newBuilder().setParent(parent)
                .setInputConfig(InputConfig.newBuilder().setUserEventInlineSource(UserEventInlineSource.newBuilder().addAllUserEvents(purchases).build()).build())
                .build();
OperationFuture<ImportUserEventsResponse, ImportMetadata> future = userEventServiceClient.importUserEventsAsync(importUserEventRequest);
while (!future.isDone()) {
    Thread.sleep(1000l);
}
ImportUserEventsResponse response = future.get();
```
When I made a userEvent .toString() the output is

```
event_type: "purchase-complete"
user_info {
  visitor_id: "032134"
}
product_event_detail {
  product_details {
    id: "0034612"
    currency_code: "EUR"
    quantity: 2
  }
  purchase_transaction {
    id: "223"
    revenue: 12.3
    currency_code: "EUR"
  }
}
event_time {
  seconds: 1592833306
}
event_source: BATCH_UPLOAD
```
So the field revenue is filled. But I  am always receiving this error:
```
Import user event from inline source with event_time = seconds: 1592833306 has invalid user event: 'transaction.revenue' is required in purchase transaction
```
Same happens if I use userEventServiceClient.writeUserEvent() instead of importUserEventsAsync

So it seems that at some point, when underneath UserEventServiceClient creates the Message, this field revenue is missing.

Am I doing something wrong? Thanks

**Comment by lesv** [comment]
@sgreenberg PTAL - do you have someone who can look into this?

**Comment by lesv** [comment]
@sgreenberg PTAL

**Comment by lesv** [comment]
@sgreenberg PTAL

**Comment by lesv** [comment]
@sgreenberg PTAL

**Comment by lesv** [comment]
email sent

**Comment by chenlei1216** [comment]
The error is thrown on the backend and does not look like a client library issue. Could you still reproduce this issue with the latest version? If so you may file a cloud support case to have a Cloud support engineer help with triaging:
https://cloud.google.com/retail/docs/getting-support

**Comment by kweinmeister** [comment]
As this error is not related to the client library, I am closing the issue in this repo. Please feel free to file a support case if it is still reproducible on the latest version. Thanks!
